name: Dev Release

on:
  push:
    branches:
      - main
      
env:
  draft: false
  channel: dev

jobs:
  dev-release:
    permissions: write-all
    name: Dev Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Install dependencies
        run: npm install

      - name: Build files
        run: npm run build

      - name: Build tarballs
        run: npm run pack

      - name: Rename tarballs
        run: |
          cd ./dist
          for file in *.tar.gz; do
              new_file="${file%-*}.tar.gz"
              if [[ "$file" != "$new_file" ]]; then
                  mv "$file" "$new_file"
                  echo "Renamed '$file' to '$new_file'"
              fi
          done

      - name: Get commit hash
        id: short-sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          draft: ${{ env.draft }}
          files: ./dist/*.tar.gz
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
