name: Dev Release

on:
  push:
    branches:
      - main
      
env:
  draft: false
  channel: dev

jobs:
  dev-release:
    permissions: write-all
    name: Dev Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Install dependencies
        run: npm install

      - name: Build files
        run: npm run build

      - name: Build tarballs
        run: npm run pack

      - name: Rename tarballs
        run: |
          for file in ./dist/modus-v${{ steps.package-version.outputs.current-version }}-*; do
            mv "$file" "${file%-*}.tar.gz"
          done
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          draft: ${{ env.draft }}
          files: ./dist/*.tar.gz
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
